# Generated by Django 4.2.20 on 2025-03-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='completed_courses',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
