# Generated by Django 4.2.20 on 2025-03-12 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_video_video_url_video_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_remove_student_completed_courses_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
