# Generated by Django 4.2.20 on 2025-03-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_completed_courses_alter_student_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='completed_courses',
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='interested_courses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=20, null=True),
        ),
    ]
