# Generated by Django 4.2.20 on 2025-03-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_semester'),
        ('students', '0008_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interested_courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='student',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
