# Generated by Django 4.2.20 on 2025-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=100)),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.course')),
            ],
        ),
    ]
