# Generated by Django 4.2.20 on 2025-03-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_description_video_test_question_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
