# Generated by Django 4.2.20 on 2025-03-14 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_completed_courses_alter_student_department_and_more'),
        ('courses', '0007_alter_certificate_date_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student'),
        ),
    ]
