# Generated by Django 4.2.20 on 2025-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_date_registered_registration_registered_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registered_at',
            new_name='date_registered',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='semester',
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted')], default='registered', max_length=20),
        ),
    ]
