# Generated by Django 4.2.20 on 2025-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_user'),
        ('courses', '0013_alter_certificate_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.IntegerField(default=0),
        ),
       
    ]
