# Generated by Django 4.2.20 on 2025-03-18 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_certificate_score_alter_certificate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='score',
        ),
    ]
