# Generated by Django 4.2.20 on 2025-03-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_certificate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
